// Characteristics LIST A (X)
export const characteristicsA = [
  ['Initiating', 'Yielding'],
  ['Firm', 'Flexible'],
  ['Driver', 'Observer'],
  ['Decides Quickly', 'Ponders decisions'],
  ['Pioneering', 'Deferring'],
  ['Eager', 'Patient'],
  ['Risking', 'Careful'],
  ['Outspoken', 'Receptive'],
  ['Enjoys Change', 'Enjoys stability'],
  ['Takes Charge', 'Takes direction'],
  ['Direct/blunt', 'Subtle/Tactful'],
  ['Pushy', 'Reticent'],
  ['Makes statements', 'Asks questions'],
  ['Insistent', 'Conforming'],
  ['Dominating', 'Compliant'],
  ['Acts', 'Hesitates'],
  ['Confrontive', 'Avoids conflict'],
  ['Outgoing', 'Introspective'],
  ['Talks', 'Listens'],
  ['Forceful', 'Accommodating'],
  ['Out in front', 'Behind the scenes'],
  ['Demand', 'Offer'],
  ['Competitive', 'Cooperative'],
  ['Extrovert', 'Introvert'],
  ['Egotistical', 'Modest'],
];

// Characteristics LIST B (Y)
export const characteristicsB = [
  ['Expressive', 'Private'],
  ['Relationship', 'Task'],
  ['Spontaneous', 'Intentional'],
  ['Gregarious/warm', 'Aloof/cool'],
  ['Unorganized', 'Organized'],
  ['Impulsive', 'Reflective'],
  ['Approachable', 'Unapproachable'],
  ['Relaxed', 'Self-controlled'],
  ['Unstructured', 'Structured'],
  ['Trusting', 'Skeptical'],
  ['Intuitive', 'Logical'],
  ['Lenient', 'Strict'],
  ['Available', 'Undisclosed'],
  ['Unrehearsed', 'Planned'],
  ['Personal', 'Impersonal'],
  ['Sympathetic', 'Rational'],
  ['Familiar', 'Reserved'],
  ['Feeling', 'Thinking'],
  ['Casual/Easy going', 'Orderly/precise'],
  ['Tolerant', 'Rigorous'],
  ['Informal', 'Formal'],
  ['Sensitive', 'Sensible'],
  ['Random', 'Methodical'],
  ['Guided by Inspiration', 'Guided by Facts'],
  ['Demonstrative', 'Undemonstrative'],
];
